import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { Seaweed_Script } from 'next/font/google'
import './globals.css'

// Importando a fonte Roboto do Google
const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'], 
  variable: '--font-roboto', 
})

const seaweedScript = Seaweed_Script({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-seaweed-script', // Variável CSS para Seaweed Script
})

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${seaweedScript.variable} antialiased bg-white h-screen w-screen flex items-center justify-center p-0 m-0 box-border`}
      >
        {children}
      </body>
    </html>
  )
}
